root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
exclude_regex = ["_test.go", ".*_templ.go"]
args_bin = []
bin = "./tmp/main"
pre_cmd = []
cmd = "make templ tailwind && go build -o ./tmp/main ."
delay = 0
exclude_dir = ["assets", "tmp", "vendor", "testdata"]
exclude_file = []
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "tpl", "tmpl", "templ", "html", "md"]
include_file = []
kill_delay = "0s"
log = "build-errors.log"
poll = false
poll_interval = 0
post_cmd = []
rerun = false
rerun_delay = 500
send_interrupt = false
stop_on_error = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
silent = false
time = false

[misc]
clean_on_exit = false

[proxy]
app_port = 3000
enabled = true
proxy_port = 3002

[screen]
clear_on_rebuild = false
keep_scroll = true
